//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2048.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public decimal PLAYER_ID { get; set; }
        public string PLAYER_NAME { get; set; }
        public Nullable<decimal> PLAYER_SCORE { get; set; }
        public Nullable<decimal> PLAYER_HIGHEST_TILE { get; set; }
        public Nullable<System.DateTime> PLAYER_DATETIME { get; set; }
    }
}
