IF OBJECT_ID('PLAYER', 'U') IS NOT NULL DROP TABLE PLAYER;

CREATE TABLE PLAYER 
    (PLAYER_ID              NUMERIC(3) NOT NULL,
     PLAYER_NAME               VARCHAR(50),
     PLAYER_SCORE                NUMERIC(10),
     PLAYER_HIGHEST_TILE        NUMERIC(5),
     PLAYER_DATETIME            DATE,
  CONSTRAINT PLAYER_PRIMARY_KEY PRIMARY KEY (PLAYER_ID));